export const menuIconSize = 13;
export const nodeDragIconSize = 28;
export const disabledMenuIconColor = 'var(--lt-border-color)';
export const controlIconSize = 20;
export const snapGridInterval = 20;
export const canvasMenuWidth = 170;
export const defaultNodeWidth = 360; // update App.css
export const defaultNodeHeight = 120; // update App.css
export const ZOOM_DURATION = 200;
export const minZoom = 0.2;
export const maxZoom = 2;
